//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toletBDdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detailsofad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detailsofad()
        {
            this.Ad = new HashSet<Ad>();
        }
    
        public string detail_id { get; set; }
        public Nullable<int> number_of_room { get; set; }
        public Nullable<int> number_of_kitchen { get; set; }
        public Nullable<int> number_of_bathroom { get; set; }
        public string size_of_flat { get; set; }
        public string additional_info { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ad> Ad { get; set; }
    }
}
