//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toletBDdb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class toletBDdbEntities1 : DbContext
    {
        public toletBDdbEntities1()
            : base("name=toletBDdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ad { get; set; }
        public virtual DbSet<Addresss> Addresss { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Detailsofad> Detailsofad { get; set; }
        public virtual DbSet<Governs> Governs { get; set; }
        public virtual DbSet<Interested> Interested { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
